### ISSUE TITLE
Error while launching the web app

### ISSUE THREAD

**Issue by marcomb** [rshk/jobcontrol#25]
I have problems launching the web app, during the startup.

The output hereafter

```
marcomb@debianmc:/opt/ckan/envs/jobcontrol/bin$ ./jobcontrol-cli --config-file /opt/ckan/envs/conf/conf.yaml web --port 5060 --debug
Traceback (most recent call last):
  File "./jobcontrol-cli", line 9, in <module>
    load_entry_point('jobcontrol==0.1a', 'console_scripts', 'jobcontrol-cli')()
  File "/opt/ckan/envs/jobcontrol/local/lib/python2.7/site-packages/jobcontrol-0.1a-py2.7.egg/jobcontrol/cli.py", line 337, in main
    cli_main_grp(obj={})
  File "/opt/ckan/envs/jobcontrol/local/lib/python2.7/site-packages/click-3.3-py2.7.egg/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/opt/ckan/envs/jobcontrol/local/lib/python2.7/site-packages/click-3.3-py2.7.egg/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/opt/ckan/envs/jobcontrol/local/lib/python2.7/site-packages/click-3.3-py2.7.egg/click/core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/ckan/envs/jobcontrol/local/lib/python2.7/site-packages/click-3.3-py2.7.egg/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/ckan/envs/jobcontrol/local/lib/python2.7/site-packages/click-3.3-py2.7.egg/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/opt/ckan/envs/jobcontrol/local/lib/python2.7/site-packages/jobcontrol-0.1a-py2.7.egg/jobcontrol/cli.py", line 292, in web
    app.config.update(jc.config['webapp'])
TypeError: 'NoneType' object is not iterable
marcomb@debianmc:/opt/ckan/envs/jobcontrol/bin$ ./jobcontrol-cli --config-file /opt/ckan/envs/conf/conf.yaml web --port 5060 > debug_jobcontrol.txt
Traceback (most recent call last):
  File "./jobcontrol-cli", line 9, in <module>
    load_entry_point('jobcontrol==0.1a', 'console_scripts', 'jobcontrol-cli')()
  File "/opt/ckan/envs/jobcontrol/local/lib/python2.7/site-packages/jobcontrol-0.1a-py2.7.egg/jobcontrol/cli.py", line 337, in main
    cli_main_grp(obj={})
  File "/opt/ckan/envs/jobcontrol/local/lib/python2.7/site-packages/click-3.3-py2.7.egg/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/opt/ckan/envs/jobcontrol/local/lib/python2.7/site-packages/click-3.3-py2.7.egg/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/opt/ckan/envs/jobcontrol/local/lib/python2.7/site-packages/click-3.3-py2.7.egg/click/core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/ckan/envs/jobcontrol/local/lib/python2.7/site-packages/click-3.3-py2.7.egg/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/ckan/envs/jobcontrol/local/lib/python2.7/site-packages/click-3.3-py2.7.egg/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/opt/ckan/envs/jobcontrol/local/lib/python2.7/site-packages/jobcontrol-0.1a-py2.7.egg/jobcontrol/cli.py", line 292, in web
    app.config.update(jc.config['webapp'])
TypeError: 'NoneType' object is not iterable
```

**Comment by rshk** [comment]
I confirm it's a bug due to an on-going change of the underlying object interface. Should be fixed in the develop branch, rolling out update ASAP
